export interface Resource {
    key?: string;
    Address: string;
    AgeServed: string;
    ApplicationProcess: string;
    Category: string;
    CoverageArea: string;
    Description: string;
    Description_es: string;
    Description_fr: string;
    Description_vi: string;
    Description_zh: string;
    Eligibility: string;
    EmailAddress: string;
    Fax: string;
    Fees: string;
    Hours: string;
    LocationCity: string;
    LocationState: string;
    ProgramName: string;
    TelephoneDescription1: string;
    TelephoneNumber1: string;
    TelephoneNumber2: string;
    TelephoneNumber2Description: string;
    Website: string;
    Zip: string;
    id: string;
    isFavorite: boolean;
}
